### ISSUE TITLE
WorkShop: Material de Apoio

### ISSUE THREAD

**Issue by milesibastos** [nodeschool/porto-alegre#1]
Fala aí @lucaslago blz?!
Estou escrevendo uma série de _posts_ com a intenção de criar um material de apoio em português para os eventos e gostaria muito do _feedback_ de vocês.

Segue o link:
https://medium.com/devexpert/aprendendo-nodejs-42e7c30b8389

thread iniciada em: https://github.com/nodeschool/rio/issues/9

**Comment by lucaslago** [comment]
E aí @milesibastos, bah cara, da hora a iniciativa e o post! Não conhecia o asciinema, muito massa! 😃 

Já rolou algum workshop aí no rio? Vamos trocar uma ideia! Queremos trazer node school para poa.

**Comment by milesibastos** [comment]
Blz @lucaslago ! Ainda não fizemos um evento pelo rio!!! mas tenho acompanhado as outras comunidades pelo brasil! Se precisar q qq ajuda é só falar!
O asciinem é maneiro msm, só fiquei triste de não conseguir "embeddar" no medium!
Essa semana vou postar mais alguns... vamos nos falando!
Grande Abraço!

**Comment by andreymoser** [comment]
Muito bacana o post @milesibastos! :+1:
